### PR TITLE
Get active projects

### PR DESCRIPTION
**Pull request by ASimpleFox**
Implemented a back-end endpoint to get all active (or inactive) projects. Takes an optional "active" boolean parameter that defaults to true. If you give it false, it'll look for all projects that are inactive, i.e. has an end-date.

Changelog:
- Implemented `getActiveProjects` endpoint
- Added relevant testing
- Added documentation
- Fixed a couple minor documentation issues
- UNRELATED to this PR: Added a .txt file in back-end utils folder that shows the fields of the current database, as well as what each field means/is intended to save. 

Notes:
- If there are no completed or active projects, the endpoint returns undefined. This should never happen in practice, but doing this so that we don't output an error on the back-end in case something does happen.

### CODE REVIEW

**Comment by carneyb3592** [comment]
The code seems fine but the build check failed, maybe take a look into that?

**Comment by carneyb3592** [comment]
Looks good!

**Review by carneyb3592 — APPROVED** [review]
Looks good!

**Review by sidlak-c137 — APPROVED** [review]
Very git :)

**Pull request merged**
